apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  template:
    metadata:
      name: myapp
      label:
        type: front-end
    spec:
      containers:
      - name: nginx-controller
        image: nginx
  replicas: 4
  selector:
    matchLabels:
      type: front-end
